name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: messaging_db
          MYSQL_USER: messaging_user
          MYSQL_PASSWORD: messaging_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      SECRET_KEY: github-actions-secret-key
      DEBUG: "1"

    steps:
      # Step 1 — Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 — Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3 — Install Dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt

      # Step 4 — Wait for MySQL
      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..30}; do
            if mysqladmin ping -h db --password=root --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting..."
            sleep 2
          done

      # Step 5 — Run Migrations
      - name: Run migrations
        run: |
          source venv/bin/activate
          python manage.py migrate --noinput

      # Step 6 — Run Tests
      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test
